-   hosts: "{{ sDeployServer }}"
    remote_user: "{{ sDeployUser }}"
    tasks:
    -   name: composer update
        shell: "ls;{{ sExecRemotePhp }} composer.phar update -vvv > {{ sDestDir }}/nohup.out"
        args:
            chdir: "{{ sDestDir }}"