-   hosts: "{{ sDeployServer }}"
    remote_user: "{{ sDeployUser }}"
    tasks:
    -   name: composer update
        composer:
            command: install
            executable: "{{sExecRemotePhp}}"
            working_dir: "{{sDestDir}}"