-   hosts: "{{ sDeployServer }}"
    remote_user: "{{ sDeployUser }}"
    tasks:
    -   name: "create dir {{ sDestDir }}/{{ _sVersion }}"
        file:
            path: "{{ sDestDir }}/{{ _sVersion }}"
            state: directory
            mode: 0755
            group: "{{ sDeployGroup }}"
            owner: "{{ sDeployUser }}"
    -   name: "extract {{ _sCodeTarFilePath }} to {{ sDestDir }}/{{ _sVersion }}"
        unarchive:
            src: "{{ _sCodeTarFilePath }}"
            dest: "{{ sDestDir }}/{{ _sVersion }}"
            mode: 0755
            group: "{{ sDeployGroup }}"
            owner: "{{ sDeployUser }}"
            remote_src: no