-   hosts: "{{ sDeployServer }}"
    remote_user: "{{ sDeployUser }}"
    tasks:
    -   name: "create dir {{ sDestDir }}/{{ sVersion }}"
        file:
            path: "{{ sDestDir }}/{{ sVersion }}"
            state: directory
            mode: 0775
            group: "{{ sDeployGroup }}"
            owner: "{{ sDeployUser }}"
    -   name: "extract {{ sCodeTarFilePath }} to {{ sDestDir }}/{{ sVersion }}"
        unarchive:
            src: "{{ sCodeTarFilePath }}"
            dest: "{{ sDestDir }}/{{ sVersion }}"
            mode: 0775
            group: "{{ sDeployGroup }}"
            owner: "{{ sDeployUser }}"
            remote_src: no